### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by sakrist** [unchartedworks/universalbuild#1]
Nice app. Would be nice add optional selection for which OS needs to be build.

**Comment by webcpu** [comment]
There could be multiple targets for the same OS. Xcode scheme doesn't have this problem, each scheme is for a specific OS, that's why I use Xcode scheme instead of OS.

**Comment by sakrist** [comment]
Hm. Maybe I miss understood then. How to make fat framework for iOS and macOS with your tool?

**Comment by webcpu** [comment]
For example, assume a fat framework support iphoneos and iphonesimulator, in other words, the fat framework supports iOS simulator and iOS devices.
If what you want is a framework for sharing code between iOS app and macOS app, then this tool doesn't support it.

**Comment by sakrist** [comment]
Ok, thanks. That actually what I was thinking.
